# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yogi at Fab Academy 2016
email:
# description: > # this means to ignore newlines until "baseurl:"
#baseurl: "/archives/2016/fablabtrivandrum/students/424" # the subpath of your site, e.g. /blog
url: "http://archive.fabacademy.org" # the base hostname & protocol for your site
twitter_username: YogiKulkarni
github_username:  yogi

# Build settings
markdown: kramdown
